"""add worlds and generation fields

Revision ID: c36d7f19947f
Revises: c8a1f0d6b0d4
Create Date: 2026-03-17 16:17:29.669435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c36d7f19947f'
down_revision: Union[str, Sequence[str], None] = 'c8a1f0d6b0d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worlds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), server_default='Nuevo mundo', nullable=False),
    sa.Column('pitch', sa.Text(), nullable=True),
    sa.Column('tone', sa.String(length=120), nullable=True),
    sa.Column('themes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_draft', sa.Text(), nullable=True),
    sa.Column('content_final', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worlds_owner_id'), 'worlds', ['owner_id'], unique=False)
    op.add_column('arcs', sa.Column('approval_status', sa.String(length=20), server_default='draft', nullable=False))
    op.add_column('campaigns', sa.Column('world_id', sa.UUID(), nullable=True))
    op.add_column('campaigns', sa.Column('brief_draft', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('campaigns', sa.Column('brief_final', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('campaigns', sa.Column('brief_status', sa.String(length=20), server_default='draft', nullable=False))
    op.add_column('campaigns', sa.Column('outline_draft', sa.Text(), nullable=True))
    op.add_column('campaigns', sa.Column('outline_final', sa.Text(), nullable=True))
    op.add_column('campaigns', sa.Column('outline_status', sa.String(length=20), server_default='draft', nullable=False))
    op.create_index(op.f('ix_campaigns_world_id'), 'campaigns', ['world_id'], unique=False)
    op.create_foreign_key(None, 'campaigns', 'worlds', ['world_id'], ['id'], ondelete='SET NULL')
    op.add_column('sessions', sa.Column('content_draft', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('content_final', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('approval_status', sa.String(length=20), server_default='draft', nullable=False))
    op.alter_column('arcs', 'approval_status', server_default=None)
    op.alter_column('campaigns', 'brief_status', server_default=None)
    op.alter_column('campaigns', 'outline_status', server_default=None)
    op.alter_column('sessions', 'approval_status', server_default=None)
    op.alter_column('worlds', 'name', server_default=None)
    op.alter_column('worlds', 'status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'approval_status')
    op.drop_column('sessions', 'content_final')
    op.drop_column('sessions', 'content_draft')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_index(op.f('ix_campaigns_world_id'), table_name='campaigns')
    op.drop_column('campaigns', 'outline_status')
    op.drop_column('campaigns', 'outline_final')
    op.drop_column('campaigns', 'outline_draft')
    op.drop_column('campaigns', 'brief_status')
    op.drop_column('campaigns', 'brief_final')
    op.drop_column('campaigns', 'brief_draft')
    op.drop_column('campaigns', 'world_id')
    op.drop_column('arcs', 'approval_status')
    op.drop_index(op.f('ix_worlds_owner_id'), table_name='worlds')
    op.drop_table('worlds')
    # ### end Alembic commands ###
